modLoader = "kotlinforforge" #mandatory
loaderVersion = "[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
[[mods]] #mandatory
modId = "hollowengine" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Hollow Engine" #mandatory
description = '''
'''

[[dependencies.hollowengine]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "hc"
mandatory = true
versionRange = "[1.19.2-1.5.6,1.19.2-1.6.0)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "kotlinscript"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

#FTBLibraries
[[dependencies.hollowengine]]
modId = "ftbteams"
mandatory = false
versionRange = "[1902.2.14,)"
ordering = "AFTER"
side = "BOTH"
