modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "All Rights Reserved"
[[mods]]
modId = "hollowengine"
version = "${file.jarVersion}"
displayName = "Hollow Engine" # Don't change it! This may break the game!
description = '''
'''

[[dependencies.hollowengine]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "hc"
mandatory = true
versionRange = "[1.19.2-1.5.7,1.19.2-1.6.0)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "kotlinscript"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

#FTBLibraries
[[dependencies.hollowengine]]
modId = "ftbteams"
mandatory = false
versionRange = "[1902.2.14,)"
ordering = "AFTER"
side = "BOTH"
